### ISSUE TITLE
Cannot authenticate user because admin user is not permitted to login via HTTP

### ISSUE THREAD

**Issue by skorup101** [kilimandjango/openshift-elastalert#3]
Hello,

I receive **AuthorizationException(403, 'Cannot authenticate user because admin user is not permitted to login via HTTP')** during startup from elastalert-ocp pod. 
Do you know if there is a setting I should change in order for it to work?

**Openshift version:** 4.5.13

**Changes I made to original .yaml file:**
```
# git diff
diff --git a/elastalert-ocp.yaml b/elastalert-ocp.yaml
index 085d0e2..f1e378a 100644
--- a/elastalert-ocp.yaml
+++ b/elastalert-ocp.yaml
@@ -79,7 +79,7 @@ items:
         from:
           kind: ImageStreamTag
           name: elastalert-ocp:v0.2.1
-          namespace: openshift-elastalert
+          namespace: openshift-hselastalert
       type: ImageChange
 - apiVersion: apps.openshift.io/v1
   kind: DeploymentConfig
@@ -152,7 +152,7 @@ items:
         from:
           kind: ImageStreamTag
           name: mailman:latest
-          namespace: openshift-elastalert
+          namespace: openshift-hselastalert
         lastTriggeredImage: quay.io/jstakun/fake-smtp@sha256:4494354dd70709390b997acfe41b5107a275a4a3aaab6f91dea3a3955d3c19dd
       type: ImageChange
 - apiVersion: v1
```

**Error logs from elastalert-ocp pod:**
```
#oc logs -n openshift-hselastalert pod/elastalert-ocp-1-2fg2j
Traceback (most recent call last):
  File "/opt/app-root/bin/elastalert-create-index", line 10, in <module>
    sys.exit(main())
  File "/opt/app-root/lib/python3.6/site-packages/elastalert/create_index.py", line 264, in main
    create_index_mappings(es_client=es, ea_index=index, recreate=args.recreate, old_ea_index=old_index)
  File "/opt/app-root/lib/python3.6/site-packages/elastalert/create_index.py", line 23, in create_index_mappings
    esversion = es_client.info()["version"]["number"]
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 259, in info
    return self.transport.perform_request("GET", "/", params=params)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/connection/http_requests.py", line 156, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/opt/app-root/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 181, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, 'Cannot authenticate user because admin user is not permitted to login via HTTP')
```

Thanks

**Comment by skorup101** [comment]
Moved issue here: https://github.com/jstakun/elastalert-ocp/issues/1
